version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: dawntreader09/proyecto:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: ${MONGO_ATLAS_URI}
      SPRING_DATA_MONGODB_BASE: ${MONGO_ATLAS_BASE}

    mem_limit: 800m
    cpus: "0.7"